### ISSUE TITLE
question about setup canvas

### ISSUE THREAD

**Issue by bardionson** [owmo-dev/token-art-tools#17]
I cannot figure out what this means: 'Your index.html file must display your work within a single canvas tag for all features to work.'

Can you help?
Do I make something like
<body>
<canvas/>
</body>

The examples I find show running createCanvas and then using parent to attach the canvas to a div.
let cnv = createCanvas(100, 100);
cnv.parent('myContainer');

But this is not working for me.

thank you

**Comment by bardionson** [comment]
sorry I figured it out. It was an error in another part of my script

**Comment by owmo-dev** [comment]
Glad you got it figured out :)
